package sensitometry.resources;

import java.util.ListResourceBundle;

/**
 * The resource bundle for Sensitometry class. <br>
 * 
 * @author Dan Fulea, 28 Apr. 2015
 * 
 */
public class SensitometryResources extends ListResourceBundle{
	/**
	 * Returns the array of strings in the resource bundle.
	 * 
	 * @return the resources.
	 */
	public Object[][] getContents() {
        return CONTENTS;
    }

    /** The resources to be localised. */
    private static final Object[][] CONTENTS = {
         // menu and form labels...
    	{ "form.icon.url", "/danfulea/resources/personal.png" },///jdf/resources/duke.png"},
		{ "icon.url", "/danfulea/resources/personal.png" },///jdf/resources/globe.gif"},

		{ "img.chart.bar", "/danfulea/resources/chart_bar.png" },
		{ "img.chart.curve", "/danfulea/resources/chart_curve.png" },
		
		{ "img.zoom.in", "/danfulea/resources/zoom_in.png" },
		{ "img.zoom.out", "/danfulea/resources/zoom_out.png" },
		{ "img.pan.left", "/danfulea/resources/arrow_left.png" },
		{ "img.pan.up", "/danfulea/resources/arrow_up.png" },
		{ "img.pan.down", "/danfulea/resources/arrow_down.png" },
		{ "img.pan.right", "/danfulea/resources/arrow_right.png" },
		{ "img.pan.refresh", "/danfulea/resources/arrow_refresh.png" },

		{ "img.accept", "/danfulea/resources/accept.png" },
		{ "img.insert", "/danfulea/resources/add.png" },
		{ "img.delete", "/danfulea/resources/delete.png" },
		{ "img.delete.all", "/danfulea/resources/bin_empty.png" },
		{ "img.view", "/danfulea/resources/eye.png" },
		{ "img.set", "/danfulea/resources/cog.png" },
		{ "img.report", "/danfulea/resources/document_prepare.png" },
		{ "img.today", "/danfulea/resources/time.png" },
		{ "img.open.file", "/danfulea/resources/open_folder.png" },
		{ "img.open.database", "/danfulea/resources/database_connect.png" },
		{ "img.save.database", "/danfulea/resources/database_save.png" },
		{ "img.substract.bkg", "/danfulea/resources/database_go.png" },
		{ "img.close", "/danfulea/resources/cross.png" },
		{ "img.about", "/danfulea/resources/information.png" },
		{ "img.printer", "/danfulea/resources/printer.png" },
		
		{ "Sensitometry.NAME", "Film sensitometry"},
		
		{"expData.unc","Estimated measurement uncertainty [%]: "},
		
        {"sensi.tab.title", "Sensitometrie"},
        {"align.tab.title", "Aliniament"},
        {"menu.file", "Fisier"},
        {"menu.file.mnemonic", new Character('F') },
        {"menu.file.exit", "Iesire"},
        {"menu.file.exit.mnemonic", new Character('I') },
        {"menu.file.saveBD", "Salvare in BD"},
        {"menu.file.saveBD.mnemonic", new Character('S') },
        {"menu.file.raport", "Raport..."},
        {"menu.file.raport.mnemonic", new Character('p') },
        {"menu.view", "Vizualizare BD"},
        {"menu.view.mnemonic", new Character('V')},
        //toolbar buttons
        {"toolBar.saveBD", "Salvare in BD"},
        {"toolBar.saveBD.mnemonic", new Character('S')},
        {"toolBar.saveBD.toolTip", "Salveaza rezultatele in baza de date"},
        {"toolBar.saveBD.iconName", "Save16"},
        {"toolBar.saveBD.iconName.url", "/Jad/images/Save16.gif"},
        {"toolBar.raport", "Raport..."},
		{"toolBar.raport.mnemonic", new Character('p')},
        {"toolBar.raport.toolTip", "Genereaza raportul rezultatelor in vederea printarii"},
        {"toolBar.raport.iconName", "raport"},
        {"toolBar.raport.iconName.url", "/Jad/images/raport.gif"},
        {"toolBar.bd", "Vizualizare BD..."},
		{"toolBar.bd.mnemonic", new Character('B')},
        {"toolBar.bd.toolTip", "Vizualizarea bazei de date si a operatiilor adecvate"},
        {"toolBar.bd.iconName", "About16"},
        {"toolBar.bd.iconName.url", "/Jad/images/About16.gif"},
        {"toolBar.exit", "Iesire"},
		{"toolBar.exit.mnemonic", new Character('I')},
        {"toolBar.exit.toolTip", "Inchiderea acestei ferestrei"},
        {"toolBar.exit.iconName", "check"},
        {"toolBar.exit.iconName.url", "/Jad/images/check.gif"},
        //Grafice
		{"graphics.XYSeries","y=DO"},
		{"graphics.XYSeries1","y=DO(min)"},
		{"graphics.XYSeries2","y=DO(med)"},
		{"graphics.XYSeries3","y=DO(max)"},
		{"graphics.XYSeries4","x=LogE(min)"},
		{"graphics.XYSeries5","y=LogE(med)"},
		{"graphics.XYSeries6","y=LogE(max)"},
        {"graphics.axes.1","Log(exposure)-relative units"},
        {"graphics.axes.2","OD-optical density"},
		{"graphics.Title","Sensitometric curve (HD-curve)"},
		{"graphics.Points","Data points"},
        //sensi
		{"tab.related.Label", "Double click on editable cells below to change values!"},
        {"tab.columns", new String[] {"Step","Log(E)","DO"}},
        {"sensi.fitCh", "use fitting function"},
        {"sensi.fitCh.tooltip", "Use fitting function for H-D curve in further calculations"},
        {"sensi.bfL","Maximum permissible optical dose (OD) for base+fog: "},
        {"sensi.contrast.minL","Permissible contrast interval: minimum: "},
        {"sensi.contrast.maxL","maximum: "},
        {"sensi.lowL","The value for low OD (begining of straight line) is not lower then: "},
        {"sensi.midL","The value for median OD (middle of straight line) is not lower then: "},
        {"sensi.highL","The value for high OD (end of straight line) is not lower then: "},
        {"sensi.addrB", "Add row"},
        {"sensi.addrB.mnemonic", new Character('A')},
        {"sensi.delrB", "Delete row"},
        {"sensi.delrB.mnemonic", new Character('D')},
        {"sensi.calcB", "Compute"},
        {"sensi.calcB.mnemonic", new Character('C')},
        {"sensi.graphB", "Grafic..."},
        {"sensi.graphB.mnemonic", new Character('G')},
        //{ "saveB", "View/Save in database" },
		//{ "saveB.toolTip", "View database and/or save in database" },
		//{ "saveB.mnemonic", new Character('w') },
		
		{ "saveB", "Pdf print..." },
		{ "saveB.toolTip", "Save report as pdf file" },
		{ "saveB.mnemonic", new Character('P') },
        //align
        {"align.devx.leftL","Deviatie 'stanga' camp X vs camp luminos (mm): "},
        {"align.devx.rightL","Deviatie 'dreapta' camp X vs camp luminos (mm): "},
        {"align.devy.bottomL","Deviatie 'jos' camp X vs camp luminos (mm): "},
        {"align.devy.topL","Deviatie 'sus' camp X vs camp luminos (mm): "},
        {"align.ffd", "FFD - Distanta focus film (cm): "},
        {"align.devmp", "Deviatia maxim permisa vs FFD (%): "},
        {"align.calcB", "Calculeaza"},
        {"align.calcB.mnemonic", new Character('C')},
        //rezultat
        {"rezultat", "Result: "},
        {"rezultat.succes", " Test PASSED!"},
        {"rezultat.fail", " Test NOT PASSED!"},

        {"sensi.rezultat.bf", "Base+fog OD = "},
        {"sensi.rezultat.bfmp", "Maximum permissible optical density (OD) for base+fog = "},
        {"sensi.rezultat.contrast", "Contrast (gamma) = "},
        {"sensi.rezultat.avegradient", "Average gradient (slope between 0.25+base+fog OD and 2.0+base+fog OD) = "},
        {"sensi.rezultat.contrast.min", "Minimum permissible contrast = "},
        {"sensi.rezultat.contrast.max", "Maximum permissible contrast = "},
        {"sensi.rezultat.latitudine", "Latitude [OD domain] = "},
        {"sensi.rezultat.latitudine.loge", "Latitude [LOG(E) domain] = "},
        {"sensi.rezultat.speed", "Sensitivity (speed indicator as LOG(E) for median value of straight line curve) = "},
        {"sensi.rezultat.speed2", "Sensitivity (speed indicator as LOG(E) for 1.0 + base+fog OD) = "},
        {"align.rezultat.devx", "Deviatia camp X vs camp luminos pe 'orizontala' (cm) = "},
        {"align.rezultat.devy", "Deviatia camp X vs camp luminos pe 'verticala' (cm) = "},
        {"align.rezultat.devmp", "Deviatia camp X vs camp luminos maxim permisa (cm) = "},
        //raport
        {"raport.category.db","Informatii generale"},
        {"raport.umed","Unitatea medicala:"},
        {"raport.sectia","Sectia:"},
        {"raport.localitate","Localitatea:"},
        {"raport.tipxinstal","Tip instalatie X:"},
        {"raport.numarserial","Numar serial:"},
        {"raport.datamasurarii","Data masuratorilor:"},
        {"raport.adresa","Adresa:"},
        {"raport.telefon","Telefon:"},
        {"raport.email","E-mail:"},
        {"raport.contact","Persoana de contact:"},

        {"raport.sensi.category.teor", "Referinte teoretice -Sensitometrie:"},
        {"raport.sensi.bfmp.teor", "Densitatea optica (DO) pentru baza+ceata maxim permisa:"},
        {"raport.sensi.contrastmin.teor", "Contrast (gama) minim permis:"},
        {"raport.sensi.contrastmax.teor", "Contrast (gama) maxim permis:"},
        {"raport.sensi.category.exp","Evaluari experimentale -Sensitometrie:"},
        {"raport.sensi.punctederetea","Valori masurate:"},
        {"raport.sensi.punctederetea.step","Step"},
        {"raport.sensi.punctederetea.loge","LogE-rel"},
        {"raport.sensi.punctederetea.do","DO"},
        {"raport.sensi.bf.exp","Densitatea optica (DO) pentru baza+ceata: "},
        {"raport.sensi.contrast.exp","Contrast (gama): "},
        {"raport.sensi.latitudine.exp","Latitudine: "},
        {"raport.sensi.speed.exp","Sensitivitate (speed): "},
        {"raport.sensi.rez","Rezultat test: "},
		{"raport.align.category.teor", "Referinte teoretice -Aliniament:"},
		{"raport.align.category.exp","Evaluari experimentale -Aliniament:"},
        {"raport.align.devmp.teor", "Deviatie liniara relativ la distanta focus-film maxim permisa (cm):"},
        {"raport.align.devx.exp", "Deviatie liniara 'orizontala' (cm):"},
        {"raport.align.devy.exp", "Deviatie liniara 'verticala' (cm):"},
        //bd
        {"viewBd.title","Vizualizare baza de date"},
        {"viewBd.align.tab.baseName","align"},
        {"viewBd.sensi.tab.baseName","sensi"},
        {"viewBd.tab.sufixName","date"},
        {"commonColumnFromUpdateTables", "id"},
        {"viewBd.recordLabel","Nr. inregistrari:"},
        {"viewBd.selectCurrentB", "Inregistrare curenta"},
        {"viewBd.selectCurrentB.mnemonic", new Character('c')},
        {"viewBd.selectAllB", "Toate inregistrarile"},
        {"viewBd.selectAllB.mnemonic", new Character('T')},
        {"viewBd.selectSelectB", "Inregistrarea selectata"},
        {"viewBd.selectSelectB.mnemonic", new Character('S')},

        {"saveDb.sensi.tab2.columns", new String[] {"nrcrt","id","step","logE","densitate_optica"}},
        {"saveDb.sensi.tab1.columns", new String[] {"id","base_fog_max_permis","base_fog",
        	"rezultat_base_fog","contrast_min_permis","contrast_max_permis","contrast",
        	"rezultat_contrast","latitudine","speed","do_low","do_mid","do_high","fit"}},
        {"saveDb.align.tab1.columns", new String[] {"id","dev_max_permis","dev_x",
        					"rezultat_x","dev_y","rezultat_y","dev_x_left","dev_x_right",
        					"dev_y_bottom","dev_y_top","focus_film_dist"}},
        {"saveDb.true", "da"},
        {"saveDb.false", "nu"},
        {"viewBd.sensi.tab.orderby","step"},
        
        //dialogs
        { "number.error.title", "Error" },
		{ "number.error.message", "Insert valid positive numbers! " },
		{ "number.error.message2", "Too few data points! " },
		{ "number.noDuplicateAscend.message", "No duplicates allowed. Ascend order required!" },
		
        {"dialog.insertInListError.title", "Eroare...."},
        {"dialog.insertInList.message", "Introduceti numere reale!"},
        {"dialog.insertInTableError.title", "Eroare...."},
        {"dialog.insertInTable.message", "Introduceti numere pozitive!"},
        {"dialog.noDuplicate.title", "Atentie!"},
		{"dialog.noDuplicate.message", "Nu introduceti duplicate.Notati ca 'loge' trebuie sa fie crescator!!"},
        {"dialog.processReportError.title", "Eroare...."},
        {"dialog.processReportError.message", "Eroare la procesarea acestui raport!"},
        {"dialog.reportError.title", "Eroare...."},
        {"dialog.reportError.message", "Eroare neasteptata la afisarea raportului!"},

        {"dialog.selectError.title", "Eroare...."},
        {"dialog.selectError.message", "Nu se poate efectua aceasta selectie!!"},
        {"dialog.alterError.title", "Eroare...."},
        {"dialog.alterError.message", "Nu se poate efectua aceasta modificare in baza de date!!"},
        {"dialog.insertError.title", "Eroare...."},
        {"dialog.insertError.message", "Nu se poate introduce in baza de date!!"},
        {"dialog.exit.title", "Confirmare inchidere..."},
        {"dialog.exit.message", "Salvati modificarile in baza de date?"},
        {"dialog.exit.buttons", new Object[]{"Da","Nu"}},
        
        { "pdf.metadata.title", "RadQC PDF" },
		{ "pdf.metadata.subject", "RadQC analysis results" },
		{ "pdf.metadata.keywords", "RadQC, PDF" },
		{ "pdf.metadata.author", "RadQC" },
		{ "pdf.content.title", "RadQC - Film sensitometry Report" },
		{ "pdf.content.subtitle", "Report generated by: " },
		{ "pdf.page", "Page " },
		{ "pdf.header", "RadQC output" },
		{ "file.extension", "pdf" },
		{ "file.description", "PDF file" },
		{ "dialog.overwrite.title", "Overwriting..." },
		{ "dialog.overwrite.message", "Are you sure?" },
		{ "dialog.overwrite.buttons", new Object[] { "Yes", "No" } },
    };
}
